from __future__ import annotations

SYNTHETIC_TRAINING_DATA = [
    ("I feel nervous all day and worry that something bad will happen", "anxiety"),
    ("My heart races and I get panic attacks before meetings", "anxiety"),
    ("I can't stop overthinking and I feel tense constantly", "anxiety"),
    ("I wake up worried and have chest tightness often", "anxiety"),
    ("I avoid social settings because fear gets overwhelming", "anxiety"),
    ("My mind keeps looping on worst case scenarios", "anxiety"),
    ("I feel restless and anxious even when things are okay", "anxiety"),
    ("I have trouble relaxing and my anxiety affects sleep", "anxiety"),
    ("I feel down every day and nothing feels enjoyable", "depression"),
    ("I have low mood, no motivation, and feel hopeless", "depression"),
    ("I sleep too much and still feel exhausted and sad", "depression"),
    ("I lost interest in hobbies and isolate from everyone", "depression"),
    ("I feel empty, guilty, and struggle to get out of bed", "depression"),
    ("My appetite changed and I feel numb and depressed", "depression"),
    ("I cry often and feel like life is not improving", "depression"),
    ("I feel worthless and have persistent sadness", "depression"),
    ("I cannot focus, get distracted, and forget tasks", "adhd"),
    ("I start many things but never finish and miss deadlines", "adhd"),
    ("I am fidgety, impulsive, and struggle to sit still", "adhd"),
    ("My attention drifts constantly and I lose track in conversations", "adhd"),
    ("I am disorganized and often misplace important items", "adhd"),
    ("I interrupt people and make impulsive decisions", "adhd"),
    ("I have lifelong concentration issues that hurt my work", "adhd"),
    ("I procrastinate heavily and can't manage priorities", "adhd"),
    ("I have flashbacks from trauma and feel on edge", "ptsd"),
    ("Nightmares about the incident keep waking me up", "ptsd"),
    ("I avoid reminders of trauma and feel constantly unsafe", "ptsd"),
    ("Loud noises trigger intense fear and intrusive memories", "ptsd"),
    ("I relive traumatic memories and have hypervigilance", "ptsd"),
    ("I feel numb, detached, and startled very easily", "ptsd"),
    ("Past trauma causes panic and sleep disturbances", "ptsd"),
    ("I get recurring memories and emotional shutdown", "ptsd"),
    ("My mood swings from very high energy to deep crashes", "bipolar"),
    ("I have periods of little sleep with racing thoughts and grand plans", "bipolar"),
    ("Some weeks I feel unstoppable then become severely depressed", "bipolar"),
    ("I talk fast, spend impulsively, and then feel hopeless", "bipolar"),
    ("I have episodes of elevated mood and risky behavior", "bipolar"),
    ("I can go days without sleep and feel overly confident", "bipolar"),
    ("My family noticed manic episodes followed by low mood", "bipolar"),
    ("I alternate between agitation and depression", "bipolar"),
    ("Anxiety makes it hard to concentrate and sleep", "anxiety"),
    ("I feel sad and anxious with little interest in anything", "depression"),
    ("I overthink simple tasks and fear making mistakes", "anxiety"),
    ("I forget appointments and cannot focus on one thing", "adhd"),
    ("Trauma reminders trigger panic and emotional withdrawal", "ptsd"),
    ("I experience high energy bursts and severe emotional crashes", "bipolar"),
    ("Persistent low mood and fatigue are affecting my job", "depression"),
    ("Panic symptoms include sweating and shaking in crowds", "anxiety"),
    ("My attention problems started in childhood and continue now", "adhd"),
    ("I avoid places linked to the traumatic event", "ptsd"),
    ("I feel euphoric for days and then deeply hopeless", "bipolar"),
]
